version: '3.9'
services:
    app:
        image: php:8.1-fpm
        container_name: php-${APP_NAME}
        restart: unless-stopped
        volumes:
            - "./:/var/www"
        networks:
          - network-dev
    nginx:
        image: nginx:alpine
        container_name: nginx-${APP_NAME}
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
          - network-dev
        depends_on:
            - app
            - mysql
    mysql:
        image: mysql:5.7
        container_name: mysql-${APP_NAME}
        restart: unless-stopped
        environment:
          MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
          MYSQL_USER: ${DB_USERNAME}
          MYSQL_PASSWORD: ${DB_PASSWORD}
          SERVICE_TAGS: dev
          SERVICE_NAME: mysql
        ports:
            - "8989:3306"
        networks:
          - network-dev

networks:
  network-dev:
    driver: bridge